const languages = {
	"Mandarin Chinese": "zh",
	"Japanese": "ja",
	"Mongolian": "mn",
	"Korean": "ko",
	"Taiwanese Hokkien": "na",
	"Hakka": "ha",
	"Pashto": "ps",
	"Dari": "pr",
	"Bengali": "bn",
	"Dzongkha": "dz",
	"Hindi": "hi",
	"English": "en",
	"Divehi": "dv",
	"Nepali": "ne",
	"Urdu": "ur",
	"Sinhala": "si",
	"Tamil": "ta",
	"Malay": "ms",
	"Khmer": "km",
	"Indonesian": "id",
	"Lao": "lo",
	"Burmese": "my",
	"Tagalog": "tl",
	"Thai": "th",
	"Tetum": "te",
	"Portuguese": "pt",
	"Vietnamese": "vi",
	"Kazakh": "kk",
	"Russian": "ru",
	"Kyrgyz": "ky",
	"Tajiki": "tg",
	"Turkmen": "tk",
	"Uzbek": "uz",
	"Armenian": "hy",
	"Azerbaijani": "az",
	"Arabic": "ar",
	"Greek": "el",
	"Turkish": "tr",
	"Georgian": "ka",
	"Kurdish": "ku",
	"Hebrew": "he",
	"French": "fr",
	"Kirundi": "rn",
	"Tigrinya": "ti",
	"Amharic": "am",
	"Oromifa": "or",
	"Somali": "so",
	"Swahili": "sw",
	"Malagasy": "mg",
	"Chichewa": "ny",
	"Mauritian Creole": "mf",
	"Kinyarwanda": "rw",
	"Seychellois Creole": "cr",
	"Shona": "sn",
	"Ndebele": "nd",
	"Tswana": "tn",
	"Swazi": "ss",
	"Sesotho": "st",
	"Afrikaans": "af",
	"IsiZulu": "zu",
	"IsiXhosa": "xh",
	"Setswana": "tn",
	"Northern Sotho": "ns",
	"Venda": "ve",
	"Xitsonga": "ts",
	"Sango": "sa",
	"Congolese (Kinshasa)": "ln",
	"Spanish": "es",
	"Albanian": "sq",
	"Catalan": "ca",
	"German": "de",
	"Belarusian": "be",
	"Dutch": "nl",
	"Bosnian": "bs",
	"Croatian": "hr",
	"Serbian": "sr",
	"Bulgarian": "bg",
	"Czech": "cs",
	"Danish": "da",
	"Estonian": "et",
	"Finnish": "fi",
	"Swedish": "sv",
	"Hungarian": "hu",
	"Icelandic": "is",
	"Irish": "ga",
	"Italian": "it",
	"Latvian": "lv",
	"Lithuanian": "lt",
	"Luxembourgish": "lb",
	"Maltese": "mt",
	"Romanian": "ro",
	"Montenegrin": "me",
	"Macedonian": "mk",
	"Norwegian": "no",
	"Polish": "pl",
	"Slovak": "sk",
	"Slovenian": "sl",
	"Romansh": "rm",
	"Ukrainian": "uk",
	"Latin": "la",
	"Quechua": "qu",
	"Aymara": "ay",
	"Guarani": "gn",
	"Haitian Creole": "ht",
	"Maori": "mi",
	"Tok Pisin": "tp",
	"Bislama": "bi",
	"Fijian": "fj",
	"Palauan": "pa",
	"Marshallese": "mh",
	"Gilbertese": "gi",
	"Nauruan": "na",
	"Tongan": "to",
	"Samoan": "sm"
}

export default languages;